POST http://127.0.0.1:8000/bedrijven/login/
content-type: application/json

{ "username": "admin", "password": "admin" }

###

POST http://127.0.0.1:8000/bedrijven/signup/
content-type: application/json

{ "username": "bryan4", "password": "bryan", "email": "bryandk@gmail.com", "website": "https://www.tweakers.net" }

###

GET http://127.0.0.1:8000/bedrijven/test_token/
content-type: application/json

{}
