# Generated by Django 5.0.1 on 2024-02-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onderzoeken',
            table='onderzoeken',
        ),
    ]
