# Generated by Django 5.0.1 on 2024-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_alter_onderzoeken_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medewerkers',
            fields=[
                ('medewerker_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=6)),
                ('huisnummer', models.IntegerField(max_length=10)),
                ('geslacht', models.CharField(max_length=10)),
                ('emailadres', models.CharField(max_length=255)),
                ('telefoonnummer', models.IntegerField(max_length=15)),
                ('geboortedatum', models.DateField()),
                ('admin', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medewerkers',
            },
        ),
    ]
