# Generated by Django 5.0.1 on 2024-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_medewerkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerkers',
            name='gebruikersnaam',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='wachtwoord',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='admin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='huisnummer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='telefoonnummer',
            field=models.CharField(max_length=15),
        ),
    ]
