# Generated by Django 5.0.1 on 2024-02-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderzoek',
            name='organisatie',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='onderzoek',
        ),
        migrations.DeleteModel(
            name='Organisatie',
        ),
        migrations.DeleteModel(
            name='Onderzoek',
        ),
    ]
