# Generated by Django 5.0.1 on 2024-02-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_alter_medewerker_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medewerker',
            name='test',
        ),
    ]
