# Generated by Django 5.0.1 on 2024-02-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_remove_medewerker_test'),
    ]

    operations = [
    ]
