# Generated by Django 5.0.2 on 2024-03-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_remove_onderzoek_organisatie_and_more'),
        ('companies', '0012_alter_onderzoek_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='benadering_keuze',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='email_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='naam_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='onderzoek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.onderzoek'),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='telefoonnummer_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='wachtwoord',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='bijzonderheden',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='hulpmiddelen',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='telefoonnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='admin',
            field=models.BooleanField(),
        ),
    ]
