# Generated by Django 5.0.1 on 2024-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_goedkeuring_ervaringsdeskundige_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='status',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
