# Generated by Django 5.0.2 on 2024-03-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_ervaringsdeskundige_benadering_keuze_and_more'),
    ]

    operations = [
    ]
