# Generated by Django 5.0.2 on 2024-03-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_ervaringsdeskundige_benadering_keuze_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoedkeuringErvaringsdeskundige',
            fields=[
                ('goedkeurings_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('datum_van_goed_keuring', models.DateField()),
                ('deskundige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.ervaringsdeskundige')),
                ('medewerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.medewerker')),
            ],
            options={
                'db_table': 'goedkeuring_ervaringsdeskundige',
            },
        ),
    ]
