# Generated by Django 5.0.1 on 2024-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0007_alter_onderzoek_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
