# Generated by Django 5.0.2 on 2024-03-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_goedkeuring_ervaringsdeskundige_and_more'),
        ('administrators', '0007_goedkeuringervaringsdeskundige'),
    ]

    operations = [
    ]
