# Generated by Django 5.0.1 on 2024-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0008_alter_onderzoek_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='admin',
            field=models.BooleanField(),
        ),
    ]
