# Generated by Django 5.0.1 on 2024-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0009_alter_medewerker_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='benadering_keuze',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='email_toezichthouder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='naam_toezichthouder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='telefoonnummer_toezichthouder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
