# Generated by Django 5.0.1 on 2024-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0012_alter_ervaringsdeskundige_telefoonnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='wachtwoord',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
