# Generated by Django 5.0.1 on 2024-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0013_ervaringsdeskundige_wachtwoord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='email_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='naam_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='telefoonnummer_toezichthouder',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
