# Generated by Django 5.0.1 on 2024-02-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('beschrijving', models.TextField()),
                ('contactpersoon', models.CharField(max_length=255)),
                ('emailadres', models.EmailField(max_length=255)),
                ('telefoonnummer', models.CharField(max_length=15)),
                ('overige_details', models.TextField()),
            ],
            options={
                'db_table': 'organisatie_organisaties',
            },
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('onderzoek_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('beschikbaar', models.CharField(max_length=50)),
                ('beschrijving', models.CharField(max_length=255)),
                ('datum_vanaf', models.DateField()),
                ('datum_tot', models.DateField()),
                ('type_onderzoek', models.CharField(max_length=50)),
                ('locatie', models.CharField(max_length=255)),
                ('met_beloning', models.BooleanField()),
                ('beloning', models.TextField(blank=True, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField()),
                ('doelgroep_leeftijd_tot', models.IntegerField()),
                ('doelgroep_beperking', models.CharField(max_length=100)),
                ('onderzoek_vragen_id', models.IntegerField()),
                ('organisatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.organisatie')),
            ],
            options={
                'db_table': 'organisatie_onderzoeken',
            },
        ),
    ]
