# Generated by Django 5.0.1 on 2024-02-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_organisatie_managers_organisatie_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisatie',
            name='emailadres',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='gebruikersnaam',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='naam',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='wachtwoord',
        ),
    ]
