# Generated by Django 5.0.1 on 2024-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_organisatie_emailadres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='naam',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
