# Generated by Django 5.0.1 on 2024-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_organisatie_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisatie',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
